//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AjustesStock
    {
        public int IdAjuste { get; set; }
        public int IdProducto { get; set; }
        public System.DateTime FechaAjuste { get; set; }
        public decimal Cantidad { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaAcceso { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
