//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.FacturasVenta = new HashSet<FacturasVenta>();
            this.Remitos = new HashSet<Remitos>();
        }
    
        public byte IdEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string NFantasia { get; set; }
        public Nullable<System.DateTime> InicioActividades { get; set; }
        public string CUIT { get; set; }
        public byte[] Logo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string IIBB { get; set; }
        public string CondicionIva { get; set; }
        public Nullable<short> CodigoPostal { get; set; }
        public Nullable<byte> SubCodigoPostal { get; set; }
        public string RutaCertificado { get; set; }
        public string SerialCertificado { get; set; }
    
        public virtual CPostales CPostales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasVenta> FacturasVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remitos> Remitos { get; set; }
    }
}
