//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogErrores
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string Origen { get; set; }
        public string Metodo { get; set; }
        public string Mensaje { get; set; }
        public string StackTrace { get; set; }
    }
}
