//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int IdProducto { get; set; }
        public int NroProducto { get; set; }
        public string CodigoBarra { get; set; }
        public string DescCorta { get; set; }
        public string DescLarga { get; set; }
        public int IdRubro { get; set; }
        public bool LlevarStock { get; set; }
        public Nullable<double> StockActual { get; set; }
        public Nullable<System.DateTime> UltimaActStock { get; set; }
        public Nullable<double> CantidadMinima { get; set; }
        public int IdUnidadMedida { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string CodigoProducto { get; set; }
        public Nullable<int> Embalaje { get; set; }
    
        public virtual Rubros Rubros { get; set; }
        public virtual UnidadesMedida UnidadesMedida { get; set; }
    }
}
