//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaProducto
    {
        public int IdProducto { get; set; }
        public string DescCorta { get; set; }
        public string DescLarga { get; set; }
        public string LlevarStock { get; set; }
        public string Stock { get; set; }
        public Nullable<System.DateTime> UltimaActStock { get; set; }
        public Nullable<double> CantidadMinima { get; set; }
        public string FechaBaja { get; set; }
        public string Rubro { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<double> StockActual { get; set; }
        public string CodigoBarra { get; set; }
        public Nullable<System.DateTime> Maxfecha { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public int IdRubro { get; set; }
        public string CodigoProducto { get; set; }
        public int IdUnidadMedida { get; set; }
        public int IdProveedor { get; set; }
        public string Proveedor { get; set; }
    }
}
